### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by tflx** [NunoPinheiro/react-i18n-helper#1]
Running 'npm install --save react-i18n-helper' gives me an npm error 'Refusing to install react-i18n-helper as a dependency of itself'.

*edit

Adding it to package dependencies worked. But now I get this on npm start:
'Failed at the react-i18n-helper@0.2.5 start script 'rackt server'.

**Comment by NunoPinheiro** [comment]
Hi,
I suppose you checked out the project and run the command inside, which meant you would be trying to download the project as a dependency to itself.
You should run the command in the project where you are going to use it, not in this project.

**Comment by tflx** [comment]
Yes, that was pretty dumb - thanks
