### ISSUE TITLE
forceUpdate is not a function

### ISSUE THREAD

**Issue by tflx** [NunoPinheiro/react-i18n-helper#2]
It seems that react doesn't have built in support for mixins when using ES6 style classes.
So I'm importing react-mixin which should help me. But I'm getting an error on changeLocale `forceUpdate is not a function.`
The initialData is loaded fine and I can see the right json being loaded on changeLocale. This is my component:

```
import React, {Component} from 'react';
import {changeLocale, i18nEventsListenerMixin, setupI18NConfiguration, i18n } from 'react-i18n-helper';
import reactMixin from 'react-mixin';

export default class Locale extends Component {

  constructor(props) {
    const initialData = {HelloWorld: 'Hello, World!'};
    super(props);
    setupI18NConfiguration({clientPath: 'static/i18n', fallBackLocale: 'en-GB', initialState: {locale: 'en-GB', data: initialData}});
  }


  state = {
    desktop: true
  };


  render() {
    return (
      <div>
        <span>{i18n('HelloWorld')}</span>
        <button onClick={() => changeLocale('pt-PT')}>pt-PT</button>
        <button onClick={() => changeLocale('en-GB')}>en-GB</button>
      </div>
    );
  }
}

reactMixin(Locale.prototype, i18nEventsListenerMixin);

```

Do you have an idea about what I'm doing wrong?...thank you

**Comment by NunoPinheiro** [comment]
Hi, I found a fix for this issue.
Could you change node_modules/react-i18n-helper/dist/react-i18n-helper.js  line 27 to 
this.i18nUnsubscribe = i18nStore.subscribe(this.reRenderOnI18NEvent.bind(this));

If it works I'll commit and update the project.

**Comment by tflx** [comment]
It works. Awesome - thanks.
