### ISSUE TITLE
Why jquery?

### ISSUE THREAD

**Issue by micky2be** [NunoPinheiro/react-i18n-helper#3]
If all you need is the ability to fetch a document on a server you could use simply `fetch` and a polyfill or something like `axios`

**Comment by NunoPinheiro** [comment]
Hi,
yes, I only used jquery because I was on the prototyping phase, and it was the library I knew how to use. 
In fact jquery brings so much stuff that it is probably a really bad option. I'll take a look at the libraries you propose.
Thanks for the feedback!

**Comment by NunoPinheiro** [comment]
Hi,
I've done what you suggested.
